# Generated by Django 4.1.3 on 2023-05-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_company_options_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='logo.png', upload_to='company_images'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='profile_image.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.student')),
            ],
        ),
    ]
